[plans]
pop_dev = 0.0001
num_dists = 4
node_data=["county", "node_name", "population","area","border_length"]
geo_units=["node_name"]
pop_col="population"
area_col="area" 
node_border_col="border_length"
edge_perimeter_col="length"
map_directory=["data","grid"]
map_file="grid_graph_4_by_4.json"

[measure]
gamma=0.0
iso_weight=0.0
measure_scores=["get_log_spanning_forests","get_isoperimetric_score"]


[mcmc]
cycle_walk_steps = 5e8
two_cycle_walk_frac = 0.3

[run]
thread_id = 1
atlasNameBase="grid4x4_cycleWalk"
outputDirectory=["output","grid"]
cycle_walk_out_freq=100
writer_stats=["get_log_spanning_trees"]
compress="gz" 
run_diagnostics=true
