name: Test CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11' # <-- Or your preferred Julia version

      - name: Install dependencies
        run: julia --project=. -e 'import Pkg; Pkg.instantiate()'

      - name: Run tests
        run: julia --project=. -e 'import Pkg; Pkg.test()'
